import { IConfig } from './types';

const Config: IConfig = {
  NAME: 'Plenty Network',
  TOKEN_CONFIG : 'http://3.88.82.46/v1/config/token' ,
  AMM_CONFIG : 'http://3.88.82.46/v1/config/amm' ,
  API: {
    url: 'https://api.coingecko.com/api/v3/coins/tezos?localization=false&tickers=false&community_data=false&developer_data=false&sparkline=false',
    API_KEY: '4824FE50-DB6E-4316-B099-72283C964891',
    tezToolTokenPrice: 'https://api.teztools.io/token/prices',
  },
  RPC_NODES: {
    testnet: 'https://ithacanet.smartpy.io/',
    mainnet: 'https://mifx20dfsr.windmill.tools/',
  },
  TZKT_NODES: {
    mainnet: 'https://api.tzkt.io',
    testnet: 'https://api.ithacanet.tzkt.io',
  },

  CTEZ: {
    mainnet: 'KT1GWnsoFZVHGh7roXEER3qeCcgJgrXT3de2',
    testnet: 'KT19xSuHb2A86eSbKVsduY8mZv4UVEBPwQ17',
  },

  TOKEN_CONTRACTS: {
    testnet: {
      PLENTY: {
        address: 'KT1Mdk7TfHjbwb2ciTTsySj9gV9W9uc7HxCu',

        mapId: 33509,
        decimal: 18,
        type: 'FA1.2',
        tokenId: 0,
      },
    },
    mainnet: {
      PLENTY: {
        address: 'KT1GRSvLoikDsXujKgZPsGLX8k8VvR2Tq95b',
        mapId: 3943,
        decimal: 18,
        type: 'FA1.2',
        tokenId: 0,
      },
      xPLENTY: {
        address: 'KT1Rpviewjg82JgjGfAKFneSupjAR1kUhbza',
        mapId: 18153,
        decimal: 18,
        type: 'FA1.2',
        tokenId: 0,
      },
      wMATIC: {
        address: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        decimal: 18,
        type: 'FA2',
        tokenId: 11,
      },
      wLINK: {
        address: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        decimal: 18,
        type: 'FA2',
        tokenId: 10,
      },
      DOGA: {
        address: 'KT1Ha4yFVeyzw6KRAdkzq6TxDHB97KG4pZe8',
        mapId: 134335,
        decimal: 5,
        type: 'FA1.2',
        tokenId: 0,
      },
      USDtz: {
        address: 'KT1LN4LPSqTMS7Sd2CJw4bbDGRkMv2t68Fy9',
        mapId: 36,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      ETHtz: {
        address: 'KT19at7rQUvyjxnZ2fBv7D9zc8rkyG7gAoU8',
        mapId: 199,
        decimal: 18,
        type: 'FA1.2',
        tokenId: 0,
      },
      hDAO: {
        address: 'KT1AFA2mwNUMNd4SsujE1YYp29vd8BZejyKW',
        mapId: 515,
        decimal: 6,
        type: 'FA2',
        tokenId: 0,
      },
      WRAP: {
        address: 'KT1LRboPna9yQY9BrjtQYDS1DVxhKESK4VVd',
        mapId: 1777,
        decimal: 8,
        type: 'FA1.2',
        tokenId: 0,
      },
      KALAM: {
        address: 'KT1A5P4ejnLix13jtadsfV9GCnXLMNnab8UT',
        mapId: 4178,
        decimal: 10,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - XTZ': {
        address: 'KT1X1LgNkQShpF9nRLYw3Dgdy4qp38MX617z',
        mapId: 3956,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      'CTEZ - DOGA': {
        address: 'KT1DZ41c1mV12oh8YNXm54JpwUNZ2C5R6VaG',
        mapId: 171789,
        decimal: 5,
        type: 'FA1.2',
        tokenId: 0,
      },
      'kUSD - USDC.e': {
        address: 'KT1J5HNUXnQwonSam3kmDQ5WbhynPPpVtgdN',
        mapId: 181898,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'uUSD - USDC.e': {
        address: 'KT1Ah4Fe2hjcRdVCiCQDhRDZ2vDYLdYNjY51',
        mapId: 181890,
        decimal: 9,
        type: 'FA1.2',
        tokenId: 0,
      },
      'USDtz - USDC.e': {
        address: 'KT1P9GyfYrW9EZ8m3jej2cMu49fpmEbYa2h5',
        mapId: 193185,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      // 'USDT.e - USDC.e': {
      //   address: 'KT1P9GyfYrW9EZ8m3jej2cMu49fpmEbYa2h5',
      //   mapId: 193185,
      //   decimal: 6,
      //   type: 'FA1.2',
      //   tokenId: 0,
      // },
      'tzBTC - WBTC.e': {
        address: 'KT1HJbndQjBEhAqR3Vj3NaP3RwFGudJf5YP4',
        mapId: 179610,
        decimal: 8,
        type: 'FA1.2',
        tokenId: 0,
      },
      'DAI.e - USDC.e': {
        address: 'KT1TupjqgajsoArMKK3ifmNveKhU2XpTJrH8',
        mapId: 187493,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ETHtz - WETH.e': {
        address: 'KT19ga4Vz26GRBdn8oibR4WFF7aDF4oE9Ch3',
        mapId: 187480,
        decimal: 18,
        type: 'FA1.2',
        tokenId: 0,
      },
      'WBTC.e - CTEZ': {
        address: 'KT1VRAYxpCo5xHYmBLYmMAWxXoVYCVgpeuak',
        mapId: 177398,
        decimal: 7,
        type: 'FA1.2',
        tokenId: 0,
      },
      'USDC.e - CTEZ': {
        address: 'KT1XpLzv4tqqsf2aLneDZgEeNFhKkH8JBGXv',
        mapId: 177380,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      'WETH.e - CTEZ': {
        address: 'KT1SDugcNjEbNQe55TdQppiRP1wVDbmxHuF1',
        mapId: 188174,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'MATIC.e - CTEZ': {
        address: 'KT18rVWWn2LMo2Hpy6KNhkhGgks21g11dxVv',
        mapId: 188159,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'LINK.e - CTEZ': {
        address: 'KT1WcS1cdwcbT3yyuYA6uzsYdZxBax5cGjdR',
        mapId: 188165,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },

      'KALAM - XTZ': {
        address: 'KT1J3wTYb4xk5BsSBkg6ML55bX1xq7desS34',
        mapId: 4353,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - wBUSD': {
        address: 'KT1UC3vcVZ4K9b39uQxaMNA2N1RuJXKLCnoA',
        mapId: 10749,
        decimal: 18,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - wUSDC': {
        address: 'KT1Gz1mx1jm7JHqU7GuMVWF6soB9RjsfLN3o',
        mapId: 10755,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - wWBTC': {
        address: 'KT1La1qZiJtDRcd9ek8w5KYD47i9MQqAQHmP',
        mapId: 11051,
        decimal: 13,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - wMATIC': {
        address: 'KT1WCGPFvy97wwGxewKfvTr1QYPvpEgUKToS',
        mapId: 11807,
        decimal: 18,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - wLINK': {
        address: 'KT1Brqb3JvXNKzwjW82F8pUAxQ7ipCfApWki',
        mapId: 11811,
        decimal: 18,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - USDtz': {
        address: 'KT18qSo4Ch2Mfq4jP3eME7SWHB8B8EDTtVBu',
        mapId: 11814,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - hDAO': {
        address: 'KT1B2SzTBtb7PgTePbDLV5BmUZQ2PC1sdSHZ',
        mapId: 12952,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - ETHtz': {
        address: 'KT1VvcbAjMWHVUbhLENpiVBejbzXYDt3PusE',
        mapId: 12955,
        decimal: 18,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - wWETH': {
        address: 'KT1SULRhejhoBWUmMnU53YHJrQZ3rxqsamdm',
        mapId: 12959,
        decimal: 18,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - kUSD': {
        address: 'KT1XTpd8JPexGxBL2dAmU9h2o9fcd9LEUG2t',
        mapId: 12963,
        decimal: 18,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - QUIPU': {
        address: 'KT1VDSyTqS95wkB4tRGy6saMa4izRKwrEg26',
        mapId: 12966,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - WRAP': {
        address: 'KT1AHndbp9xVpaJrfTHfYzSXKHDVHMdKxcW2',
        mapId: 14096,
        decimal: 13,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - UNO': {
        address: 'KT1B6ALzWXQp5wUavuo2VTMNjRdTGm8wx37w',
        mapId: 14100,
        decimal: 13,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - SMAK': {
        address: 'KT1NLZah1MKeWuveQvdsCqAUCjksKw8J296z',
        mapId: 14107,
        decimal: 10,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - KALAM': {
        address: 'KT1G3QTnrpWNhZr9x3Prprw3GH6gAMqV113D',
        mapId: 14104,
        decimal: 14,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - tzBTC': {
        address: 'KT1SqQimKz3RbQbckpSHhn4nanUmDuRqkFH3',
        mapId: 14093,
        decimal: 13,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - uUSD': {
        address: 'KT1E8CrG6uznYAG9vZVGtApMJwwTScxPEUKq',
        mapId: 15796,
        decimal: 14,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - GIF': {
        address: 'KT1MVLRQ7K7275oHDvbtKcUzNJsPBstZGKUp',
        mapId: 17061,
        decimal: 13,
        type: 'FA1.2',
        tokenId: 0,
      },
      'CTEZ - TEZ': {
        address: 'KT1DMnJvNrFYc8N9Ptxhw3NtqKN7AWqxCpkS',
        mapId: 171168,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - YOU': {
        address: 'KT1UaU5fbSYqYeFmhmsjLkqQXZ1ZG54Qs2vh',
        mapId: 20020,
        decimal: 15,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - wDAI': {
        address: 'KT19vdNapeT6MALXvkvW745KiVKGXmD4AZq5',
        mapId: 20016,
        decimal: 18,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - wUSDT': {
        address: 'KT1PcM1LUqgVdkXqKvZ4CeC9aiwLgYYCEHMH',
        mapId: 20024,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'PLENTY - cTez': {
        address: 'KT1LdX5pUkZZGwYPePcAFSpETbqfbGCwJpfw',
        mapId: 21490,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'uUSD - wUSDC': {
        address: 'KT1A2W6mBjn49yqzjJbt9T7xNVD9gDeL45qD',
        mapId: 22767,
        decimal: 9,
        type: 'FA1.2',
        tokenId: 0,
      },
      'uUSD - YOU': {
        address: 'KT1Tmncfgpp4ZSp6aEogL7uhBqHTiKsSPegK',
        mapId: 22770,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'uUSD - uDEFI': {
        address: 'KT1RQvdYD9yc763j8FiVLyXbKPVVbZqGRx5m',
        mapId: 22802,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - kUSD': {
        address: 'KT19bFNh8pZCRtTy7Pi9kpEcb2Yd7KWArAik',
        mapId: 44750,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - USDtz': {
        address: 'KT1DQfEUBsaZo43G3j1CbFF9BiWZXS72DuCh',
        mapId: 44781,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - wUSDC': {
        address: 'KT19bFNh8pZCRtTy7Pi9kpEcb2Yd7KWArAik',
        mapId: 44803,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - wUSDT': {
        address: 'KT1KgCx6CYVSyLxfiFdo5hVuMwZBPQy1XZaf',
        mapId: 44806,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - wBUSD': {
        address: 'KT1K7GRKUWzfNJ9jzGprb13XDVqqp6GE67ZU',
        mapId: 44819,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - wDAI': {
        address: 'KT1VLLdUaMfFbJw87b1PaVG1ac6UYM5xzqC5',
        mapId: 44829,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - KALAM': {
        address: 'KT1N3mKQMnWEwt4FB3J4qP2X8LwYgndGDZrn',
        mapId: 44834,
        decimal: 8,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - GIF': {
        address: 'KT1KdPxrn7UTx6CUWxuUBaGx4bVv6ZJKWUWr',
        mapId: 44857,
        decimal: 7,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - ETHtz': {
        address: 'KT1GAvdLT9tkpKkRmkuChuL9T83esBtatgKm',
        mapId: 44870,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - QUIPU': {
        address: 'KT1C6Q4Mnnpns8vSQy7kJitZNMsED24SMw9m',
        mapId: 44884,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - hDAO': {
        address: 'KT1DidqBuSaxGbVaDq2gLVkfh262dYyoGeSH',
        mapId: 44890,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - kDAO': {
        address: 'KT1KmkH1T2CQV2Q5AcMeZy3GHhwNac48FBap',
        mapId: 44912,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - wWETH': {
        address: 'KT1BAiXZkKG4R9W7LAKiAQahC8Wg7ZpJBaEs',
        mapId: 44916,
        decimal: 12,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - uUSD': {
        address: 'KT1BX8F7Xrtsy1tJ91iLovu4nJ8ZyVv4Dac2',
        mapId: 44924,
        decimal: 9,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - FLAME': {
        address: 'KT1UfvQiYexnpag6rZ3LMGsn5YFiEHrXrtbq',
        mapId: 44943,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - SMAK': {
        address: 'KT1NeR3ExLddfdAbs5nwpQMm6DqBekyJTc4R',
        mapId: 44946,
        decimal: 4,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - crDAO': {
        address: 'KT1MQcJCLZL8ASHYGmT5LVzeXV64ruy7RAuH',
        mapId: 44954,
        decimal: 7,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - PXL': {
        address: 'KT1GhzTxzgXgdv1rRCppAB5D4poXiUgp8yoU',
        mapId: 44994,
        decimal: 6,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - UNO': {
        address: 'KT1WKWhTNMY4h4eHunbsnJ1oAtDWXCz4qNQm',
        mapId: 45316,
        decimal: 7,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - WRAP': {
        address: 'KT1MX73dim8HKqQLjTHvkJnpRUp37C1HXdkt',
        mapId: 44767,
        decimal: 7,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - wWBTC': {
        address: 'KT1XWRUcvtcgpsETcasdUnNkq9rJeWmz8ihD',
        mapId: 44790,
        decimal: 7,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - tzBTC': {
        address: 'KT1TMZjKBvSVKzETZTyRsTxYEu4uZLLs6VpJ',
        mapId: 44904,
        decimal: 7,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - PAUL': {
        address: 'KT1N93veCzepAPydFGGUhDFiA69PoawasxXi',
        mapId: 46392,
        decimal: 7,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - CRUNCH': {
        address: 'KT1QSA2SMDEKzEnJhGrVGheWb94Ux8Wyfuy6',
        mapId: 44763,
        decimal: 7,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - INSTA': {
        address: 'KT1GkTwzN2gR6UdBicDSu2JEaRtv5KAPunrj',
        mapId: 44957,
        decimal: 7,
        type: 'FA1.2',
        tokenId: 0,
      },
      'ctez - DOGA': {
        address: 'KT1DZ41c1mV12oh8YNXm54JpwUNZ2C5R6VaG',
        mapId: 171789,
        decimal: 5,
        type: 'FA1.2',
        tokenId: 0,
      },
    },
  },
  SERVERLESS_BASE_URL: {
    mainnet: 'https://w0sujgfj39.execute-api.us-east-2.amazonaws.com/v1',
    testnet: 'https://testnet.dummy-api.us-east-10.amazonaws.com/v1',
  },
  SERVERLESS_REQUEST: {
    mainnet: {
      'HOME-PAGE-TVL': '/tvl',
      'PLENTY-STATS': '/homestats',
    },
    testnet: {},
  },
  ROUTER: {
    mainnet: 'KT1MEVCrGRCsoERXf6ahNLC4ik6J2vRH7Mm6',
    testnet: 'KT1FMZVMeyCrNFyGjJfiB6VSq3LX1ShSEzuw',
  },
  STABLESWAP: {
    testnet: {
      ctez: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1HZW9FWJt6aU8x4nr6UiBry2eUCA7xEFb1',
        mapId: 26976,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          tez: {
            contract: 'KT1AD4khq2R9q6DDbRY5CvUk8MXoshqsatGS',
            property: 'ctezPool',
            liquidityToken: 'ctez-XTZ-LP',
            type: 'xtz',
          },
        },
      },
      tez: {
        ICON: '',
        TOKEN_CONTRACT: '',
        READ_TYPE: 'XTZ',
        CALL_TYPE: 'XTZ',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1AD4khq2R9q6DDbRY5CvUk8MXoshqsatGS',
            property: 'tezPool',
            liquidityToken: 'ctez-XTZ-LP',
            type: 'xtz',
          },
        },
      },
      'ctez-XTZ-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Rp1fLJPFiR3w5iYSB1zxz4aDWL3Biiqhy',
        mapId: 80419,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {},
      },
    },
    mainnet: {
      ctez: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1SjXiUX63QvdNMcM2m492f7kuf8JxXRLp4',
        mapId: 20920,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          tez: {
            contract: 'KT1CAYNQGvYSF5UvHK21grMrKpe2563w9UcX',
            property: 'ctezPool',
            liquidityToken: 'ctez-XTZ-LP',
            type: 'xtz',
          },
        },
      },

      tez: {
        ICON: '',
        TOKEN_CONTRACT: '',
        READ_TYPE: 'XTZ',
        CALL_TYPE: 'XTZ',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1CAYNQGvYSF5UvHK21grMrKpe2563w9UcX',
            property: 'tezPool',
            liquidityToken: 'ctez-XTZ-LP',
            type: 'xtz',
          },
        },
      },
      uUSD: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW',
        mapId: 7706,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        DEX_PAIRS: {
          'USDC.e': {
            contract: 'KT1Ji4hVDeQ5Ru7GW1Tna9buYSs3AppHLwj9',
            property: 'token2_pool',
            liquidityToken: 'usdc.e-uusd-LP',
            type: 'veStableAMM',
          },
        },
      },
      tzBTC: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn',
        mapId: 31,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 8,
        DEX_PAIRS: {
          'WBTC.e': {
            contract: 'KT1Ws4qpXFVRKctB5mJcahFVcpcUi2WbxWM3',
            property: 'token2_pool',
            liquidityToken: 'tzbtc-wbtc.e-LP',
            type: 'veStableAMM',
          },
        },
      },
      kUSD: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1K9gCRgaLRFKTErYt1wVxA3Frb9FjasjTV',
        mapId: 380,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          'USDC.e': {
            contract: 'KT1HgFcDE8ZXNdT1aXXKpMbZc6GkUS2VHiPo',
            property: 'token2_pool',
            liquidityToken: 'usdc.e-kusd-LP',
            type: 'veStableAMM',
          },
        },
      },
      'WBTC.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 1,
        TOKEN_DECIMAL: 8,
        DEX_PAIRS: {
          tzBTC: {
            contract: 'KT1Ws4qpXFVRKctB5mJcahFVcpcUi2WbxWM3',
            property: 'token1_pool',
            liquidityToken: 'tzbtc-wbtc.e-LP',
            type: 'veStableAMM',
          },
        },
      },
      'USDC.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 2,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          kUSD: {
            contract: 'KT1HgFcDE8ZXNdT1aXXKpMbZc6GkUS2VHiPo',
            property: 'token1_pool',
            liquidityToken: 'usdc.e-kusd-LP',
            type: 'veStableAMM',
          },
          uUSD: {
            contract: 'KT1Ji4hVDeQ5Ru7GW1Tna9buYSs3AppHLwj9',
            property: 'token1_pool',
            liquidityToken: 'usdc.e-uusd-LP',
            type: 'veStableAMM',
          },
          'DAI.e': {
            contract: 'KT1Hxn43imdKTWXEZsLVdoUsS1R4hWTSXgDs',
            property: 'token2_pool',
            liquidityToken: 'dai.e-usdc.e-LP',
            type: 'veStableAMM',
          },
          USDtz: {
            contract: 'KT1995R6hTYzXjV52mGtf6MboPRhzbJBJe6q',
            property: 'token1_pool',
            liquidityToken: 'usdtz-usdc.e-LP',
            type: 'veStableAMM',
          },
          'BUSD.e': {
            contract: 'KT1LutmpUK8TDkA19tLCQNr7Eh7kbEsP3uiP',
            property: 'token1_pool',
            liquidityToken: 'busd.e-usdc.e-LP',
            type: 'veStableAMM',
          },
          // 'USDT.e': {
          //   contract: 'KT1LutmpUK8TDkA19tLCQNr7Eh7kbEsP3uiP',
          //   property: 'token1_pool',
          //   liquidityToken: 'usdt.e-usdc.e-LP',
          //   type: 'veStableAMM',
          // },
        },
      },

      'DAI.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 6,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          'USDC.e': {
            contract: 'KT1Hxn43imdKTWXEZsLVdoUsS1R4hWTSXgDs',
            property: 'token1_pool',
            liquidityToken: 'dai.e-usdc.e-LP',
            type: 'veStableAMM',
          },
        },
      },

      USDtz: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1LN4LPSqTMS7Sd2CJw4bbDGRkMv2t68Fy9',
        mapId: 36,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          'USDC.e': {
            contract: 'KT1995R6hTYzXjV52mGtf6MboPRhzbJBJe6q',
            property: 'token2_pool',
            liquidityToken: 'usdtz-usdc.e-LP',
            type: 'veStableAMM',
          },
        },
      },

      // 'USDT.e': {
      //   ICON: '',
      //      TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
      //      mapId: 175082,
      //      READ_TYPE: 'FA2',
      //      CALL_TYPE: 'FA2',
      //      TOKEN_ID: 3,
      //      TOKEN_DECIMAL: 6,
      //   DEX_PAIRS: {
      //     'USDC.e': {
      //       contract: 'KT1995R6hTYzXjV52mGtf6MboPRhzbJBJe6q',
      //       property: 'token2_pool',
      //       liquidityToken: 'usdt.e-usdc.e-LP',
      //       type: 'veStableAMM',
      //     },
      //   },
      // },

      'BUSD.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 7,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          'USDC.e': {
            contract: 'KT1LutmpUK8TDkA19tLCQNr7Eh7kbEsP3uiP',
            property: 'token2_pool',
            liquidityToken: 'busd.e-usdc.e-LP',
            type: 'veStableAMM',
          },
        },
      },

      ETHtz: {
        ICON: '',
        TOKEN_CONTRACT: 'KT19at7rQUvyjxnZ2fBv7D9zc8rkyG7gAoU8',
        mapId: 199,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          'WETH.e': {
            contract: 'KT1BKcLyaaNf2SHfAivBFBqdFoYTjuc78Aff',
            property: 'token2_pool',
            liquidityToken: 'ethtz-weth.e-LP',
            type: 'veStableAMM',
          },
        },
      },

      'WETH.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          ETHtz: {
            contract: 'KT1BKcLyaaNf2SHfAivBFBqdFoYTjuc78Aff',
            property: 'token1_pool',
            liquidityToken: 'ethtz-weth.e-LP',
            type: 'veStableAMM',
          },
        },
      },

      // 'usdt.e-usdc.e-LP': {
      //   ICON: '',
      //   TOKEN_CONTRACT: 'KT1P9GyfYrW9EZ8m3jej2cMu49fpmEbYa2h5',
      //   mapId: 193185,
      //   READ_TYPE: 'FA1.2',
      //   TOKEN_ID: 0,
      //   TOKEN_DECIMAL: 6,
      //   CALL_TYPE: 'FA1.2',
      //   DEX_PAIRS: {},
      // },

      'usdtz-usdc.e-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1P9GyfYrW9EZ8m3jej2cMu49fpmEbYa2h5',
        mapId: 193185,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },
      'busd.e-usdc.e-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1G76qEBDqmAXLCCVg4ZuNbrENsxFe8aECe',
        mapId: 193188,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },

      'dai.e-usdc.e-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1TupjqgajsoArMKK3ifmNveKhU2XpTJrH8',
        mapId: 187493,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },

      'ethtz-weth.e-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT19ga4Vz26GRBdn8oibR4WFF7aDF4oE9Ch3',
        mapId: 187480,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },

      'tzbtc-wbtc.e-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1HJbndQjBEhAqR3Vj3NaP3RwFGudJf5YP4',
        mapId: 179610,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 8,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },

      'usdc.e-kusd-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1J5HNUXnQwonSam3kmDQ5WbhynPPpVtgdN',
        mapId: 181898,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },

      'usdc.e-uusd-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Ah4Fe2hjcRdVCiCQDhRDZ2vDYLdYNjY51',
        mapId: 181890,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 9,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },
      'ctez-XTZ-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1DMnJvNrFYc8N9Ptxhw3NtqKN7AWqxCpkS',
        mapId: 171168,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {},
      },
    },
  },
  AMM: {
    testnet: {
      ctez: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1HZW9FWJt6aU8x4nr6UiBry2eUCA7xEFb1',
        mapId: 26976,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          tez: {
            contract: 'KT1AD4khq2R9q6DDbRY5CvUk8MXoshqsatGS',
            property: 'ctezPool',
            liquidityToken: 'ctez-XTZ-LP',
            type: 'xtz',
          },
          'DAI.e': {
            contract: 'KT1Gt8rQtPn6DSNnnZ1JGcf1CVdHA6CZhRAJ',
            property: 'token2_pool',
            liquidityToken: 'CTEZ-DAI.E-LP',
            type: 'oldAMM',
          },
          'BUSD.e': {
            contract: 'KT1UavMEguhWjJ8WdAujpco3tyXyXkKUYyby',
            property: 'token2_pool',
            liquidityToken: 'CTEZ-BUSD.E-LP',
            type: 'oldAMM',
          },
          PLENTY: {
            contract: 'KT1DWBEpG82w6VEVTDV2Z9NEWUe5Xxu9CH1G',
            property: 'token1_pool',
            liquidityToken: 'ctezPlentyLP',
            type: 'oldAMM',
          },
        },
      },
      'DAI.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1EZBn43coqL6xfT5xL6e49nhEPLp9B8m4n',
        mapId: 162915,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 7,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1Gt8rQtPn6DSNnnZ1JGcf1CVdHA6CZhRAJ',
            property: 'token1_pool',
            liquidityToken: 'CTEZ-DAI.E-LP',
            type: 'oldAMM',
          },
        },
      },
      tez: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1XL89VUosEQh5Dk9fBBwrepXBw7V4EdqL5',
        READ_TYPE: 'XTZ',
        CALL_TYPE: 'XTZ',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1AD4khq2R9q6DDbRY5CvUk8MXoshqsatGS',
            property: 'tezPool',
            liquidityToken: 'ctez-XTZ-LP',
            type: 'xtz',
          },
        },
      },
      'BUSD.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1EZBn43coqL6xfT5xL6e49nhEPLp9B8m4n',
        mapId: 162915,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1UavMEguhWjJ8WdAujpco3tyXyXkKUYyby',
            property: 'token1_pool',
            liquidityToken: 'CTEZ-BUSD.E-LP',
            type: 'oldAMM',
          },
        },
      },
      PLENTY: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Mdk7TfHjbwb2ciTTsySj9gV9W9uc7HxCu',
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          wWETH: {
            contract: 'KT1RG7ouxNLs5Mtdz9xKQyWDtxcC3LPuXcZF',
            property: 'token2_pool',
            liquidityToken: 'PlentyWETHLP',
            type: 'oldAMM',
          },
          wUSDC: {
            contract: 'KT1NBrkfVDM42B9q7hJcNwx1efcntwDF8fzf',
            property: 'token2_pool',
            liquidityToken: 'PlentyUSDCLP',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1DWBEpG82w6VEVTDV2Z9NEWUe5Xxu9CH1G',
            property: 'token2_pool',
            liquidityToken: 'ctezPlentyLP',
            type: 'oldAMM',
          },
          wDAI: {
            contract: 'KT1Qc52zbRaKi5cwCBnx8o4FSDbdxuePLqYB',
            property: 'token2_pool',
            liquidityToken: 'PltDaiLp',
            type: 'oldAMM',
          },
          WRAP: {
            contract: 'KT1HePFs4aA5u6A5BDw3ot7LuXvqa4ebqrTQ',
            property: 'token2_pool',
            liquidityToken: 'WrapLP',
            type: 'oldAMM',
          },
        },
      },
      WRAP: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1L1xYJit22TmuhDXaeng4AZDhRqZwcacNj',
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 8,
        CALL_TYPE: 'FA2',
        DEX_PAIRS: {
          wDAI: {
            contract: 'KT1PnFKMA2v1ngvYUh5UKtaDuM5WxskrunFm',
            property: 'token1_pool',
            liquidityToken: 'WrapDaiLp',
            type: 'oldAMM',
          },
          PLENTY: {
            contract: 'KT1HePFs4aA5u6A5BDw3ot7LuXvqa4ebqrTQ',
            property: 'token1_pool',
            liquidityToken: 'WrapLP',
            type: 'oldAMM',
          },
        },
      },
      wDAI: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1DJwRryZ11dGDnqmmRtTiSsgxQDY4bw3j4',
        READ_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA2',
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1Qc52zbRaKi5cwCBnx8o4FSDbdxuePLqYB',
            property: 'token1_pool',
            liquidityToken: 'PltDaiLp',
            type: 'oldAMM',
          },
          WRAP: {
            contract: 'KT1PnFKMA2v1ngvYUh5UKtaDuM5WxskrunFm',
            property: 'token2_pool',
            liquidityToken: 'WrapDaiLp',
            type: 'oldAMM',
          },
        },
      },
      wUSDC: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Bjfjuwfpgm5R3iXq8PBM9zqd3jEK2jiy5',
        mapId: 34178,
        READ_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        CALL_TYPE: 'FA2',
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1NBrkfVDM42B9q7hJcNwx1efcntwDF8fzf',
            property: 'token1_pool',
            liquidityToken: 'PlentyUSDCLP',
            type: 'oldAMM',
          },
        },
      },
      wWETH: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Bjfjuwfpgm5R3iXq8PBM9zqd3jEK2jiy5',
        mapId: 34178,
        READ_TYPE: 'FA2',
        TOKEN_ID: 1,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA2',
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1RG7ouxNLs5Mtdz9xKQyWDtxcC3LPuXcZF',
            property: 'token1_pool',
            liquidityToken: 'PlentyWETHLP',
            type: 'oldAMM',
          },
        },
      },
      WrapLP: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1LHy8buFGtsZJjMc4C89Wk8VTowqaUwPbY',
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 13,
        CALL_TYPE: 'FA1.2',
      },
      PltDaiLp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1CAmNNoetuxeYZWJLSmbh9N66SDYT8tkBJ',
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 13,
        CALL_TYPE: 'FA1.2',
      },
      WrapDaiLp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1LcFzpTtkDtZwHty12PSuEsscxMPtdA2ZR',
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 13,
        CALL_TYPE: 'FA1.2',
      },
      'CTEZ-DAI.E-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Q4Z7DWPE7piJJ5ZkWmCqtP7o3EgfBr4s5',
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
      },
      'CTEZ-BUSD.E-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Ta8cCFkxGLx8UFzQQLqFSbzk5RAu8aTZj',
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
      },
      ctezPlentyLP: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1ESYSFLGWtmxZFoQG6vMkMt6Cqo73vjS57',
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-XTZ-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Rp1fLJPFiR3w5iYSB1zxz4aDWL3Biiqhy',
        mapId: 80419,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {},
      },
      PlentyWETHLP: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1XReQKShV1t62JKyFAKUqHcnAdLFMpnTu7',
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
      },
      PlentyUSDCLP: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1H2w5EZKJeGSeMLrRBuASfN1YoaUmotnSB',
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
    },
    mainnet: {
      tez: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1BG1oEqQckYBRBCyaAcq1iQXkp8PVXhSVr',
        READ_TYPE: 'XTZ',
        CALL_TYPE: 'XTZ',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1CAYNQGvYSF5UvHK21grMrKpe2563w9UcX',
            property: 'tezPool',
            liquidityToken: 'ctez-XTZ-LP',
            type: 'xtz',
          },
        },
      },
      PLENTY: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1GRSvLoikDsXujKgZPsGLX8k8VvR2Tq95b',
        mapId: 3943,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          wUSDC: {
            contract: 'KT1PuPNtDFLR6U7e7vDuxunDoKasVT6kMSkz',
            property: 'token2_pool',
            liquidityToken: 'PlentywUSDClp',
            type: 'oldAMM',
          },
          wBUSD: {
            contract: 'KT1XXAavg3tTj12W1ADvd3EEnm1pu6XTmiEF',
            property: 'token2_pool',
            liquidityToken: 'PlentywBUSDlp',
            type: 'oldAMM',
          },
          wWBTC: {
            contract: 'KT19Dskaofi6ZTkrw3Tq4pK7fUqHqCz4pTZ3',
            property: 'token2_pool',
            liquidityToken: 'PlentywWBTClp',
            type: 'oldAMM',
          },
          wMATIC: {
            contract: 'KT1VeNQa4mucRj36qAJ9rTzm4DTJKfemVaZT',
            property: 'token2_pool',
            liquidityToken: 'PlentywMaticlp',
            type: 'oldAMM',
          },
          wLINK: {
            contract: 'KT1XVrXmWY9AdVri6KpxKo4CWxizKajmgzMt',
            property: 'token2_pool',
            liquidityToken: 'Plentywlinklp',
            type: 'oldAMM',
          },
          USDtz: {
            contract: 'KT1D36ZG99YuhoCRZXLL86tQYAbv36bCq9XM',
            property: 'token2_pool',
            liquidityToken: 'Plentyusdtzlp',
            type: 'oldAMM',
          },
          hDAO: {
            contract: 'KT1XutoFJ9dXvWxT7ttG86N2tSTUEpatFVTm',
            property: 'token2_pool',
            liquidityToken: 'Plenty-hDAO-LP',
            type: 'oldAMM',
          },
          ETHtz: {
            contract: 'KT1AbuUaPQmYLsB8n8FdSzBrxvrsm8ctwW1V',
            property: 'token2_pool',
            liquidityToken: 'Plenty-ETHtz-LP',
            type: 'oldAMM',
          },
          wWETH: {
            contract: 'KT1HUnqM6xFJa51PM2xHfLs7s6ARvXungtyq',
            property: 'token2_pool',
            liquidityToken: 'Plenty-wWETH-LP',
            type: 'oldAMM',
          },
          kUSD: {
            contract: 'KT1UNBvCJXiwJY6tmHM7CJUVwNPew53XkSfh',
            property: 'token2_pool',
            liquidityToken: 'PLENTY-kUSD-LP',
            type: 'oldAMM',
          },
          QUIPU: {
            contract: 'KT1NtsnKQ1c3rYB12ZToP77XaJs8WDBvF221',
            property: 'token2_pool',
            liquidityToken: 'Plenty-QUIPU-LP',
            type: 'oldAMM',
          },
          WRAP: {
            contract: 'KT1C2SXoGcje3VVMJHKRVhYXuWuNmv5ztJcw',
            property: 'token2_pool',
            liquidityToken: 'Plentywraplp',
            type: 'oldAMM',
          },
          UNO: {
            contract: 'KT1Wu8fGYxX5DfxYP8P97ZUNzrXFKjsWm7dD',
            property: 'token2_pool',
            liquidityToken: 'Plenty-UNO-LP',
            type: 'oldAMM',
          },
          KALAM: {
            contract: 'KT1HZkD2T4uczgYkZ6fb9gm1fymeJoRuezLz',
            property: 'token2_pool',
            liquidityToken: 'Plentykalamlp',
            type: 'oldAMM',
          },
          SMAK: {
            contract: 'KT1BEC9uHmADgVLXCm3wxN52qJJ85ohrWEaU',
            property: 'token2_pool',
            liquidityToken: 'Plenty-SMAK-LP',
            type: 'oldAMM',
          },
          tzBTC: {
            contract: 'KT1HaDP8fRW7kavK2beST7o4RvzuvZbn5VwV',
            property: 'token2_pool',
            liquidityToken: 'PlentytzBTClp',
            type: 'oldAMM',
          },
          uUSD: {
            contract: 'KT1Cba383ZJpEearqnUyUKUMsgu5Z3TXBgeH',
            property: 'token2_pool',
            liquidityToken: 'Plenty-uUSD-LP',
            type: 'oldAMM',
          },
          GIF: {
            contract: 'KT1Cge8y4JG6Bi8dGKf1bUfpCAv2AiW6MjtW',
            property: 'token2_pool',
            liquidityToken: 'PlentyGiflp',
            type: 'oldAMM',
          },
          YOU: {
            contract: 'KT1EM6NjJdJXmz3Pj13pfu3MWVDwXEQnoH3N',
            property: 'token2_pool',
            liquidityToken: 'Plenty-YOU-LP',
            type: 'oldAMM',
          },
          wUSDT: {
            contract: 'KT1Bi4yoALg6tuP4PKaFNDtSsDdpGLrDiGAS',
            property: 'token2_pool',
            liquidityToken: 'PlentywUSDTlp',
            type: 'oldAMM',
          },
          wDAI: {
            contract: 'KT1KDmpYSDogNtEtEnEaHQLaySuqLr8aEfJW',
            property: 'token2_pool',
            liquidityToken: 'PlentywDAIlp',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1C9gJRfkpPbNdBn3XyYbrUHT6XgfPzZqXP',
            property: 'token2_pool',
            liquidityToken: 'PlentyCtezlp',
            type: 'oldAMM',
          },
        },
      },
      wUSDC: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 17,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1PuPNtDFLR6U7e7vDuxunDoKasVT6kMSkz',
            property: 'token1_pool',
            liquidityToken: 'PlentywUSDClp',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1PZpbmKtGE6ZyYeF8entfjuGGT7CRUCF5g',
            property: 'token1_pool',
            liquidityToken: 'ctez-wusdc-lp',
            type: 'oldAMM',
          },
          uUSD: {
            contract: 'KT1JbUFVGrMCpW39UtH97dMkG2nMMrefQLLa',
            property: 'token1_pool',
            liquidityToken: 'uusd-wusdc-LP',
            type: 'oldAMM',
          },
        },
      },
      wBUSD: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 1,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1XXAavg3tTj12W1ADvd3EEnm1pu6XTmiEF',
            property: 'token1_pool',
            liquidityToken: 'PlentywBUSDlp',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1GN7PHpFsH43ypFyE2hxNMdxqTuiCGm4Pm',
            property: 'token1_pool',
            liquidityToken: 'ctez-wbusd-lp',
            type: 'oldAMM',
          },
        },
      },
      wWBTC: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 19,
        TOKEN_DECIMAL: 8,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT19Dskaofi6ZTkrw3Tq4pK7fUqHqCz4pTZ3',
            property: 'token1_pool',
            liquidityToken: 'PlentywWBTClp',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1XPUvZHc1YKTJYnGbB755V95hDgvS1qQYf',
            property: 'token1_pool',
            liquidityToken: 'ctez-wwbtc-lp',
            type: 'oldAMM',
          },
        },
      },
      wUSDT: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 18,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1Bi4yoALg6tuP4PKaFNDtSsDdpGLrDiGAS',
            property: 'token1_pool',
            liquidityToken: 'PlentywUSDTlp',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1AfTwam4bNPawLv4bWqSj9GsVDPsf5F5bQ',
            property: 'token1_pool',
            liquidityToken: 'ctez-wusdt-lp',
            type: 'oldAMM',
          },
        },
      },
      wDAI: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 5,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1KDmpYSDogNtEtEnEaHQLaySuqLr8aEfJW',
            property: 'token1_pool',
            liquidityToken: 'PlentywDAIlp',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1L5qd9xPWjiEX6ZNovhaty228ASg6jCE5p',
            property: 'token1_pool',
            liquidityToken: 'ctez-wdai-lp',
            type: 'oldAMM',
          },
        },
      },
      wMATIC: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 11,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1VeNQa4mucRj36qAJ9rTzm4DTJKfemVaZT',
            property: 'token1_pool',
            liquidityToken: 'PlentywMaticlp',
            type: 'oldAMM',
          },
        },
      },
      wLINK: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 10,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1XVrXmWY9AdVri6KpxKo4CWxizKajmgzMt',
            property: 'token1_pool',
            liquidityToken: 'Plentywlinklp',
            type: 'oldAMM',
          },
        },
      },
      wWETH: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 20,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1HUnqM6xFJa51PM2xHfLs7s6ARvXungtyq',
            property: 'token1_pool',
            liquidityToken: 'Plenty-wWETH-LP',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1WwqM2MH38PSQbECxPngBVLSbqJUHzCFAH',
            property: 'token1_pool',
            liquidityToken: 'ctez-wweth-lp',
            type: 'oldAMM',
          },
        },
      },
      UNO: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1ErKVqEhG9jxXgUG2KGLW3bNM7zXHX8SDF',
        mapId: 10978,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 9,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1Wu8fGYxX5DfxYP8P97ZUNzrXFKjsWm7dD',
            property: 'token1_pool',
            liquidityToken: 'Plenty-UNO-LP',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1XLFZ2RS8vCUmHwBG39mq7zELhnLKn9JUz',
            property: 'token1_pool',
            liquidityToken: 'ctez-uno-lp',
            type: 'oldAMM',
          },
        },
      },
      uUSD: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW',
        mapId: 7706,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        DEX_PAIRS: {
          'USDC.e': {
            contract: 'KT1Ji4hVDeQ5Ru7GW1Tna9buYSs3AppHLwj9',
            property: 'token2_pool',
            liquidityToken: 'usdc.e-uusd-LP',
            type: 'veStableAMM',
          },
          PLENTY: {
            contract: 'KT1Cba383ZJpEearqnUyUKUMsgu5Z3TXBgeH',
            property: 'token1_pool',
            liquidityToken: 'Plenty-uUSD-LP',
            type: 'oldAMM',
          },
          wUSDC: {
            contract: 'KT1JbUFVGrMCpW39UtH97dMkG2nMMrefQLLa',
            property: 'token2_pool',
            liquidityToken: 'uusd-wusdc-LP',
            type: 'oldAMM',
          },
          YOU: {
            contract: 'KT1TnrLFrdemNZ1AnnWNfi21rXg7eknS484C',
            property: 'token2_pool',
            liquidityToken: 'uusd-you-LP',
            type: 'oldAMM',
          },
          uDEFI: {
            contract: 'KT1EAw8hL5zseB3SLpJhBqPQfP9aWrWh8iMW',
            property: 'token2_pool',
            liquidityToken: 'uusd-udefi-LP',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1Rx3pQzsn4FBuuYhcWsqUS7vWFx3ktqSWD',
            property: 'token1_pool',
            liquidityToken: 'ctez-uusd-lp',
            type: 'oldAMM',
          },
        },
      },
      uDEFI: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1XRPEPXbZK25r3Htzp2o1x7xdMMmfocKNW',
        mapId: 7706,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 1,
        TOKEN_DECIMAL: 12,
        DEX_PAIRS: {
          uUSD: {
            contract: 'KT1EAw8hL5zseB3SLpJhBqPQfP9aWrWh8iMW',
            property: 'token1_pool',
            liquidityToken: 'uusd-udefi-LP',
            type: 'oldAMM',
          },
        },
      },
      YOU: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Xobej4mc6XgEjDoJoHtTKgbD1ELMvcQuL',
        mapId: 7715,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1EM6NjJdJXmz3Pj13pfu3MWVDwXEQnoH3N',
            property: 'token1_pool',
            liquidityToken: 'Plenty-YOU-LP',
            type: 'oldAMM',
          },
          uUSD: {
            contract: 'KT1TnrLFrdemNZ1AnnWNfi21rXg7eknS484C',
            property: 'token1_pool',
            liquidityToken: 'uusd-you-LP',
            type: 'oldAMM',
          },
        },
      },
      USDtz: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1LN4LPSqTMS7Sd2CJw4bbDGRkMv2t68Fy9',
        mapId: 36,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1D36ZG99YuhoCRZXLL86tQYAbv36bCq9XM',
            property: 'token1_pool',
            liquidityToken: 'Plentyusdtzlp',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1PWAXfPatPWBNJUxTHin4ECin1kYJHHnsr',
            property: 'token1_pool',
            liquidityToken: 'ctez-usdtz-lp',
            type: 'oldAMM',
          },
          'USDC.e': {
            contract: 'KT1995R6hTYzXjV52mGtf6MboPRhzbJBJe6q',
            property: 'token2_pool',
            liquidityToken: 'usdtz-usdc.e-LP',
            type: 'veStableAMM',
          },
        },
      },
      WRAP: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1LRboPna9yQY9BrjtQYDS1DVxhKESK4VVd',
        mapId: 1777,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 8,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1C2SXoGcje3VVMJHKRVhYXuWuNmv5ztJcw',
            property: 'token1_pool',
            liquidityToken: 'Plentywraplp',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT19Qe4KbEVAiaVeNsgo9Tkqa6qvZho8c4W5',
            property: 'token1_pool',
            liquidityToken: 'ctez-wrap-lp',
            type: 'oldAMM',
          },
        },
      },
      GIF: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1XTxpQvo7oRCqp85LikEZgAZ22uDxhbWJv',
        mapId: 7654,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 9,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1Cge8y4JG6Bi8dGKf1bUfpCAv2AiW6MjtW',
            property: 'token1_pool',
            liquidityToken: 'PlentyGiflp',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1VnFPwDGJRt5ufMgcWafM2WWcZCC77gpT3',
            property: 'token1_pool',
            liquidityToken: 'ctez-gif-lp',
            type: 'oldAMM',
          },
        },
      },
      tzBTC: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1PWx2mnDueood7fEmfbBDKx1D9BAnnXitn',
        mapId: 31,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 8,
        DEX_PAIRS: {
          'WBTC.e': {
            contract: 'KT1Ws4qpXFVRKctB5mJcahFVcpcUi2WbxWM3',
            property: 'token2_pool',
            liquidityToken: 'tzbtc-wbtc.e-LP',
            type: 'veStableAMM',
          },
          PLENTY: {
            contract: 'KT1HaDP8fRW7kavK2beST7o4RvzuvZbn5VwV',
            property: 'token1_pool',
            liquidityToken: 'PlentytzBTClp',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1Wryxte8NnVCm569yb8dcSPmvFBVs4ufD6',
            property: 'token1_pool',
            liquidityToken: 'ctez-tzbtc-lp',
            type: 'oldAMM',
          },
        },
      },
      ctez: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1SjXiUX63QvdNMcM2m492f7kuf8JxXRLp4',
        mapId: 20920,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          'USDC.e': {
            contract: 'KT1Dhy1gVW3PSC9cms9QJ7xPMPPpip2V9aA6',
            property: 'token1_pool',
            liquidityToken: 'usdc.e-ctez-LP',
            type: 'veAMM',
          },
          'WBTC.e': {
            contract: 'KT1KapPE9E65fBozpJqsuCgaLPytvKQduPvF',
            property: 'token1_pool',
            liquidityToken: 'wbtc.e-ctez-LP',
            type: 'veAMM',
          },
          'WETH.e': {
            contract: 'KT1Qs52cCz1gLK8LYi6cZJm7YjExg6MYLdkG',
            property: 'token1_pool',
            liquidityToken: 'weth.e-ctez-LP',
            type: 'veAMM',
          },
          'MATIC.e': {
            contract: 'KT1DiaHKX1jveXp1HGLE8X3MdxA13SLDRT7S',
            property: 'token1_pool',
            liquidityToken: 'matic.e-ctez-LP',
            type: 'veAMM',
          },
          'LINK.e': {
            contract: 'KT1GGaeBoJNxD3ieHtRiJhmcMguVLroksBGn',
            property: 'token1_pool',
            liquidityToken: 'link.e-ctez-LP',
            type: 'veAMM',
          },
          tez: {
            contract: 'KT1CAYNQGvYSF5UvHK21grMrKpe2563w9UcX',
            property: 'ctezPool',
            liquidityToken: 'ctez-XTZ-LP',
            type: 'xtz',
          },
          DOGA: {
            contract: 'KT1NLxs6rSYaJikjuCRVbVfg3p9ehfVuQgHC',
            property: 'token1_pool',
            liquidityToken: 'ctez-doga-lp',
            type: 'veAMM',
          },
          PLENTY: {
            contract: 'KT1C9gJRfkpPbNdBn3XyYbrUHT6XgfPzZqXP',
            property: 'token1_pool',
            liquidityToken: 'PlentyCtezlp',
            type: 'oldAMM',
          },
          kUSD: {
            contract: 'KT1X1nkqJDR1UHwbfpcnME5Z7agJLjUQNguB',
            property: 'token2_pool',
            liquidityToken: 'ctez-kusd-lp',
            type: 'oldAMM',
          },
          WRAP: {
            contract: 'KT19Qe4KbEVAiaVeNsgo9Tkqa6qvZho8c4W5',
            property: 'token2_pool',
            liquidityToken: 'ctez-wrap-lp',
            type: 'oldAMM',
          },
          USDtz: {
            contract: 'KT1PWAXfPatPWBNJUxTHin4ECin1kYJHHnsr',
            property: 'token2_pool',
            liquidityToken: 'ctez-usdtz-lp',
            type: 'oldAMM',
          },
          wWBTC: {
            contract: 'KT1XPUvZHc1YKTJYnGbB755V95hDgvS1qQYf',
            property: 'token2_pool',
            liquidityToken: 'ctez-wwbtc-lp',
            type: 'oldAMM',
          },
          wUSDC: {
            contract: 'KT1PZpbmKtGE6ZyYeF8entfjuGGT7CRUCF5g',
            property: 'token2_pool',
            liquidityToken: 'ctez-wusdc-lp',
            type: 'oldAMM',
          },
          wUSDT: {
            contract: 'KT1AfTwam4bNPawLv4bWqSj9GsVDPsf5F5bQ',
            property: 'token2_pool',
            liquidityToken: 'ctez-wusdt-lp',
            type: 'oldAMM',
          },
          wBUSD: {
            contract: 'KT1GN7PHpFsH43ypFyE2hxNMdxqTuiCGm4Pm',
            property: 'token2_pool',
            liquidityToken: 'ctez-wbusd-lp',
            type: 'oldAMM',
          },
          wDAI: {
            contract: 'KT1L5qd9xPWjiEX6ZNovhaty228ASg6jCE5p',
            property: 'token2_pool',
            liquidityToken: 'ctez-wdai-lp',
            type: 'oldAMM',
          },
          KALAM: {
            contract: 'KT1HuZVo3ZKRhkaHDsYXZ2fvmVfkY1FrbEDj',
            property: 'token2_pool',
            liquidityToken: 'ctez-kalam-lp',
            type: 'oldAMM',
          },
          GIF: {
            contract: 'KT1VnFPwDGJRt5ufMgcWafM2WWcZCC77gpT3',
            property: 'token2_pool',
            liquidityToken: 'ctez-gif-lp',
            type: 'oldAMM',
          },
          ETHtz: {
            contract: 'KT1GSYhwanehtwCK3NPfkMFbD1bNQmvosbqL',
            property: 'token2_pool',
            liquidityToken: 'ctez-ethtz-lp',
            type: 'oldAMM',
          },
          QUIPU: {
            contract: 'KT1Ss8rb1UFVqG2LYEU5g4NEbK5SqW5Xadwp',
            property: 'token2_pool',
            liquidityToken: 'ctez-quipu-lp',
            type: 'oldAMM',
          },
          hDAO: {
            contract: 'KT1RSxExbbRwQdYBpRHWup9vxvw1Hp25vFVM',
            property: 'token2_pool',
            liquidityToken: 'ctez-hdao-lp',
            type: 'oldAMM',
          },
          tzBTC: {
            contract: 'KT1Wryxte8NnVCm569yb8dcSPmvFBVs4ufD6',
            property: 'token2_pool',
            liquidityToken: 'ctez-tzbtc-lp',
            type: 'oldAMM',
          },
          wWETH: {
            contract: 'KT1WwqM2MH38PSQbECxPngBVLSbqJUHzCFAH',
            property: 'token2_pool',
            liquidityToken: 'ctez-wweth-lp',
            type: 'oldAMM',
          },
          uUSD: {
            contract: 'KT1Rx3pQzsn4FBuuYhcWsqUS7vWFx3ktqSWD',
            property: 'token2_pool',
            liquidityToken: 'ctez-uusd-lp',
            type: 'oldAMM',
          },
          SMAK: {
            contract: 'KT1Qg4FmXDmViQgyYLT5QkgZQSmPKvKjZbzn',
            property: 'token2_pool',
            liquidityToken: 'ctez-smak-lp',
            type: 'oldAMM',
          },
          UNO: {
            contract: 'KT1XLFZ2RS8vCUmHwBG39mq7zELhnLKn9JUz',
            property: 'token2_pool',
            liquidityToken: 'ctez-uno-lp',
            type: 'oldAMM',
          },
          CRUNCH: {
            contract: 'KT1WZztBneC9NrhVqvo9yXq8St7p8c1JVTxm',
            property: 'token2_pool',
            liquidityToken: 'ctez-crunch-lp',
            type: 'oldAMM',
          },
          PXL: {
            contract: 'KT1WR19YA8Go6GbTvtrMpUEEGSuQYxgz2ZVW',
            property: 'token2_pool',
            liquidityToken: 'ctez-pxl-lp',
            type: 'oldAMM',
          },
          INSTA: {
            contract: 'KT1EnESbHxmzd2XeENyYNege4L5TKxeatJk9',
            property: 'token2_pool',
            liquidityToken: 'ctez-insta-lp',
            type: 'oldAMM',
          },
          crDAO: {
            contract: 'KT1JkHBYp3Pq4TRSkFdc2CRoXFgDkJrfCqUe',
            property: 'token2_pool',
            liquidityToken: 'ctez-crdao-lp',
            type: 'oldAMM',
          },
          FLAME: {
            contract: 'KT1Bp3JAeeMP4GvJaspFw6zah6WydqqqHPNw',
            property: 'token2_pool',
            liquidityToken: 'ctez-flame-lp',
            type: 'oldAMM',
          },
          kDAO: {
            contract: 'KT1SP9WsMeLFTiHBXqEumTASYbF3CXh22aVV',
            property: 'token2_pool',
            liquidityToken: 'ctez-kdao-lp',
            type: 'oldAMM',
          },
          PAUL: {
            contract: 'KT1LixgLzdK4nseeD6MmmVpokuw9CvpVX9KW',
            property: 'token2_pool',
            liquidityToken: 'ctez-paul-lp',
            type: 'oldAMM',
          },
        },
      },
      DOGA: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Ha4yFVeyzw6KRAdkzq6TxDHB97KG4pZe8',
        mapId: 134335,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 5,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1NLxs6rSYaJikjuCRVbVfg3p9ehfVuQgHC',
            property: 'token2_pool',
            liquidityToken: 'ctez-doga-lp',
            type: 'veAMM',
          },
        },
      },
      PAUL: {
        ICON: '',
        TOKEN_CONTRACT: 'KT19DUSZw7mfeEATrbWVPHRrWNVbNnmfFAE6',
        mapId: 6901,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 8,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1LixgLzdK4nseeD6MmmVpokuw9CvpVX9KW',
            property: 'token1_pool',
            liquidityToken: 'ctez-paul-lp',
            type: 'oldAMM',
          },
        },
      },
      KALAM: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1A5P4ejnLix13jtadsfV9GCnXLMNnab8UT',
        mapId: 4178,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 10,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1HZkD2T4uczgYkZ6fb9gm1fymeJoRuezLz',
            property: 'token1_pool',
            liquidityToken: 'Plentykalamlp',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1HuZVo3ZKRhkaHDsYXZ2fvmVfkY1FrbEDj',
            property: 'token1_pool',
            liquidityToken: 'ctez-kalam-lp',
            type: 'oldAMM',
          },
        },
      },
      kUSD: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1K9gCRgaLRFKTErYt1wVxA3Frb9FjasjTV',
        mapId: 380,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          'USDC.e': {
            contract: 'KT1HgFcDE8ZXNdT1aXXKpMbZc6GkUS2VHiPo',
            property: 'token2_pool',
            liquidityToken: 'usdc.e-kusd-LP',
            type: 'veStableAMM',
          },
          PLENTY: {
            contract: 'KT1UNBvCJXiwJY6tmHM7CJUVwNPew53XkSfh',
            property: 'token1_pool',
            liquidityToken: 'PLENTY-kUSD-LP',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1X1nkqJDR1UHwbfpcnME5Z7agJLjUQNguB',
            property: 'token1_pool',
            liquidityToken: 'ctez-kusd-lp',
            type: 'oldAMM',
          },
        },
      },
      hDAO: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1AFA2mwNUMNd4SsujE1YYp29vd8BZejyKW',
        mapId: 515,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1XutoFJ9dXvWxT7ttG86N2tSTUEpatFVTm',
            property: 'token1_pool',
            liquidityToken: 'Plenty-hDAO-LP',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1RSxExbbRwQdYBpRHWup9vxvw1Hp25vFVM',
            property: 'token1_pool',
            liquidityToken: 'ctez-hdao-lp',
            type: 'oldAMM',
          },
        },
      },
      ETHtz: {
        ICON: '',
        TOKEN_CONTRACT: 'KT19at7rQUvyjxnZ2fBv7D9zc8rkyG7gAoU8',
        mapId: 199,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1AbuUaPQmYLsB8n8FdSzBrxvrsm8ctwW1V',
            property: 'token1_pool',
            liquidityToken: 'Plenty-ETHtz-LP',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1GSYhwanehtwCK3NPfkMFbD1bNQmvosbqL',
            property: 'token1_pool',
            liquidityToken: 'ctez-ethtz-lp',
            type: 'oldAMM',
          },
          'WETH.e': {
            contract: 'KT1BKcLyaaNf2SHfAivBFBqdFoYTjuc78Aff',
            property: 'token2_pool',
            liquidityToken: 'ethtz-weth.e-LP',
            type: 'veStableAMM',
          },
          // wWETH: {
          //   contract: 'KT196bPdVJqY1DF3y7aQ9Cn5tcGQeMrrjWTp',
          //   property: 'token1_pool',
          //   liquidityToken: 'wWETH-ETHtz-LP',
          // },
        },
      },
      SMAK: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1TwzD6zV3WeJ39ukuqxcfK2fJCnhvrdN1X',
        mapId: 1798,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 3,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1BEC9uHmADgVLXCm3wxN52qJJ85ohrWEaU',
            property: 'token1_pool',
            liquidityToken: 'Plenty-SMAK-LP',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1Qg4FmXDmViQgyYLT5QkgZQSmPKvKjZbzn',
            property: 'token1_pool',
            liquidityToken: 'ctez-smak-lp',
            type: 'oldAMM',
          },
        },
      },
      QUIPU: {
        ICON: '',
        TOKEN_CONTRACT: 'KT193D4vozYnhGJQVtw7CoxxqphqUEEwK6Vb',
        mapId: 12043,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          PLENTY: {
            contract: 'KT1NtsnKQ1c3rYB12ZToP77XaJs8WDBvF221',
            property: 'token1_pool',
            liquidityToken: 'Plenty-QUIPU-LP',
            type: 'oldAMM',
          },
          ctez: {
            contract: 'KT1Ss8rb1UFVqG2LYEU5g4NEbK5SqW5Xadwp',
            property: 'token1_pool',
            liquidityToken: 'ctez-quipu-lp',
            type: 'oldAMM',
          },
        },
      },
      CRUNCH: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1BHCumksALJQJ8q8to2EPigPW6qpyTr7Ng',
        mapId: 2809,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 8,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1WZztBneC9NrhVqvo9yXq8St7p8c1JVTxm',
            property: 'token1_pool',
            liquidityToken: 'ctez-crunch-lp',
            type: 'oldAMM',
          },
        },
      },
      FLAME: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Wa8yqRBpFCusJWgcQyjhRz7hUQAmFxW7j',
        mapId: 2545,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1Bp3JAeeMP4GvJaspFw6zah6WydqqqHPNw',
            property: 'token1_pool',
            liquidityToken: 'ctez-flame-lp',
            type: 'oldAMM',
          },
        },
      },
      kDAO: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1JkoE42rrMBP9b2oDhbx6EUr26GcySZMUH',
        mapId: 7250,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1SP9WsMeLFTiHBXqEumTASYbF3CXh22aVV',
            property: 'token1_pool',
            liquidityToken: 'ctez-kdao-lp',
            type: 'oldAMM',
          },
        },
      },
      INSTA: {
        ICON: '',
        TOKEN_CONTRACT: 'KT19y6R8x53uDKiM46ahgguS6Tjqhdj2rSzZ',
        mapId: 13802,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 9,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1EnESbHxmzd2XeENyYNege4L5TKxeatJk9',
            property: 'token1_pool',
            liquidityToken: 'ctez-insta-lp',
            type: 'oldAMM',
          },
        },
      },
      crDAO: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1XPFjZqCULSnqfKaaYy8hJjeY63UNSGwXg',
        mapId: 4666,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 8,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1JkHBYp3Pq4TRSkFdc2CRoXFgDkJrfCqUe',
            property: 'token1_pool',
            liquidityToken: 'ctez-crdao-lp',
            type: 'oldAMM',
          },
        },
      },
      PXL: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1F1mn2jbqQCJcsNgYKVAQjvenecNMY2oPK',
        mapId: 21182,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1WR19YA8Go6GbTvtrMpUEEGSuQYxgz2ZVW',
            property: 'token1_pool',
            liquidityToken: 'ctez-pxl-lp',
            type: 'oldAMM',
          },
        },
      },
      'WBTC.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 1,
        TOKEN_DECIMAL: 8,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1KapPE9E65fBozpJqsuCgaLPytvKQduPvF',
            property: 'token2_pool',
            liquidityToken: 'wbtc.e-ctez-LP',
            type: 'veAMM',
          },
          tzBTC: {
            contract: 'KT1Ws4qpXFVRKctB5mJcahFVcpcUi2WbxWM3',
            property: 'token1_pool',
            liquidityToken: 'tzbtc-wbtc.e-LP',
            type: 'veStableAMM',
          },
        },
      },
      'USDC.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 2,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1Dhy1gVW3PSC9cms9QJ7xPMPPpip2V9aA6',
            property: 'token2_pool',
            liquidityToken: 'usdc.e-ctez-LP',
            type: 'veAMM',
          },
          kUSD: {
            contract: 'KT1HgFcDE8ZXNdT1aXXKpMbZc6GkUS2VHiPo',
            property: 'token1_pool',
            liquidityToken: 'usdc.e-kusd-LP',
            type: 'veStableAMM',
          },
          uUSD: {
            contract: 'KT1Ji4hVDeQ5Ru7GW1Tna9buYSs3AppHLwj9',
            property: 'token1_pool',
            liquidityToken: 'usdc.e-uusd-LP',
            type: 'veStableAMM',
          },
          'DAI.e': {
            contract: 'KT1Hxn43imdKTWXEZsLVdoUsS1R4hWTSXgDs',
            property: 'token2_pool',
            liquidityToken: 'dai.e-usdc.e-LP',
            type: 'veStableAMM',
          },
          USDtz: {
            contract: 'KT1995R6hTYzXjV52mGtf6MboPRhzbJBJe6q',
            property: 'token1_pool',
            liquidityToken: 'usdtz-usdc.e-LP',
            type: 'veStableAMM',
          },
          'BUSD.e': {
            contract: 'KT1LutmpUK8TDkA19tLCQNr7Eh7kbEsP3uiP',
            property: 'token1_pool',
            liquidityToken: 'busd.e-usdc.e-LP',
            type: 'veStableAMM',
          },
          // 'USDT.e': {
          //   contract: 'KT1LutmpUK8TDkA19tLCQNr7Eh7kbEsP3uiP',
          //   property: 'token1_pool',
          //   liquidityToken: 'usdt.e-usdc.e-LP',
          //   type: 'veStableAMM',
          // },
        },
      },
      'LINK.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 5,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1GGaeBoJNxD3ieHtRiJhmcMguVLroksBGn',
            property: 'token2_pool',
            liquidityToken: 'link.e-ctez-LP',
            type: 'veAMM',
          },
        },
      },

      'MATIC.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 4,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          ctez: {
            contract: 'KT1DiaHKX1jveXp1HGLE8X3MdxA13SLDRT7S',
            property: 'token2_pool',
            liquidityToken: 'matic.e-ctez-LP',
            type: 'veAMM',
          },
        },
      },

      'DAI.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 6,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          'USDC.e': {
            contract: 'KT1Hxn43imdKTWXEZsLVdoUsS1R4hWTSXgDs',
            property: 'token1_pool',
            liquidityToken: 'dai.e-usdc.e-LP',
            type: 'veStableAMM',
          },
        },
      },

      'WETH.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          ETHtz: {
            contract: 'KT1BKcLyaaNf2SHfAivBFBqdFoYTjuc78Aff',
            property: 'token1_pool',
            liquidityToken: 'ethtz-weth.e-LP',
            type: 'veStableAMM',
          },
          ctez: {
            contract: 'KT1Qs52cCz1gLK8LYi6cZJm7YjExg6MYLdkG',
            property: 'token2_pool',
            liquidityToken: 'weth.e-ctez-LP',
            type: 'veAMM',
          },
        },
      },

      // 'USDT.e': {
      //   ICON: '',
      //      TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
      //      mapId: 175082,
      //      READ_TYPE: 'FA2',
      //      CALL_TYPE: 'FA2',
      //      TOKEN_ID: 3,
      //      TOKEN_DECIMAL: 6,
      //   DEX_PAIRS: {
      //     'USDC.e': {
      //       contract: 'KT1995R6hTYzXjV52mGtf6MboPRhzbJBJe6q',
      //       property: 'token2_pool',
      //       liquidityToken: 'usdt.e-usdc.e-LP',
      //       type: 'veStableAMM',
      //     },
      //   },
      // },

      'BUSD.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        READ_TYPE: 'FA2',
        CALL_TYPE: 'FA2',
        TOKEN_ID: 7,
        TOKEN_DECIMAL: 18,
        DEX_PAIRS: {
          'USDC.e': {
            contract: 'KT1LutmpUK8TDkA19tLCQNr7Eh7kbEsP3uiP',
            property: 'token2_pool',
            liquidityToken: 'busd.e-usdc.e-LP',
            type: 'veStableAMM',
          },
        },
      },

      // 'usdt.e-usdc.e-LP': {
      //   ICON: '',
      //   TOKEN_CONTRACT: 'KT1P9GyfYrW9EZ8m3jej2cMu49fpmEbYa2h5',
      //   mapId: 193185,
      //   READ_TYPE: 'FA1.2',
      //   TOKEN_ID: 0,
      //   TOKEN_DECIMAL: 6,
      //   CALL_TYPE: 'FA1.2',
      //   DEX_PAIRS: {},
      // },

      'usdtz-usdc.e-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1P9GyfYrW9EZ8m3jej2cMu49fpmEbYa2h5',
        mapId: 193185,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },
      'busd.e-usdc.e-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1G76qEBDqmAXLCCVg4ZuNbrENsxFe8aECe',
        mapId: 193188,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },

      'dai.e-usdc.e-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1TupjqgajsoArMKK3ifmNveKhU2XpTJrH8',
        mapId: 187493,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },

      'ethtz-weth.e-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT19ga4Vz26GRBdn8oibR4WFF7aDF4oE9Ch3',
        mapId: 187480,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },

      'weth.e-ctez-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1SDugcNjEbNQe55TdQppiRP1wVDbmxHuF1',
        mapId: 188174,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },

      'matic.e-ctez-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT18rVWWn2LMo2Hpy6KNhkhGgks21g11dxVv',
        mapId: 188159,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },

      'link.e-ctez-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1WcS1cdwcbT3yyuYA6uzsYdZxBax5cGjdR',
        mapId: 188165,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
        DEX_PAIRS: {},
      },

      'usdc.e-ctez-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1XpLzv4tqqsf2aLneDZgEeNFhKkH8JBGXv',
        mapId: 177380,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        CALL_TYPE: 'FA1.2',
      },
      'wbtc.e-ctez-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1VRAYxpCo5xHYmBLYmMAWxXoVYCVgpeuak',
        mapId: 177398,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 7,
        CALL_TYPE: 'FA1.2',
      },
      'tzbtc-wbtc.e-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1HJbndQjBEhAqR3Vj3NaP3RwFGudJf5YP4',
        mapId: 179610,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 8,
        CALL_TYPE: 'FA1.2',
      },
      'usdc.e-kusd-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1J5HNUXnQwonSam3kmDQ5WbhynPPpVtgdN',
        mapId: 181898,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'usdc.e-uusd-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Ah4Fe2hjcRdVCiCQDhRDZ2vDYLdYNjY51',
        mapId: 181890,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 9,
        CALL_TYPE: 'FA1.2',
      },

      PlentywBUSDlp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UC3vcVZ4K9b39uQxaMNA2N1RuJXKLCnoA',
        mapId: 10749,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
      },
      PlentywUSDClp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Gz1mx1jm7JHqU7GuMVWF6soB9RjsfLN3o',
        mapId: 10755,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      PlentywWBTClp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1La1qZiJtDRcd9ek8w5KYD47i9MQqAQHmP',
        mapId: 11051,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 13,
        CALL_TYPE: 'FA1.2',
      },
      PlentywMaticlp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1WCGPFvy97wwGxewKfvTr1QYPvpEgUKToS',
        mapId: 11807,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
      },
      Plentywlinklp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Brqb3JvXNKzwjW82F8pUAxQ7ipCfApWki',
        mapId: 11811,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
      },
      Plentyusdtzlp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18qSo4Ch2Mfq4jP3eME7SWHB8B8EDTtVBu',
        mapId: 11814,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'kUSD-USDtz-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1HEdGi7rq1zgZ68dhAtKMZYKeD3EM5vYdf',
        mapId: 11946,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'wUSDC-USDtz-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1FaoPYSyT4itmgTncvdshV7SeqqXk9RJXd',
        mapId: 11950,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        CALL_TYPE: 'FA1.2',
      },
      'Plenty-hDAO-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1B2SzTBtb7PgTePbDLV5BmUZQ2PC1sdSHZ',
        mapId: 12952,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'Plenty-ETHtz-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1VvcbAjMWHVUbhLENpiVBejbzXYDt3PusE',
        mapId: 12955,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
      },
      'Plenty-wWETH-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1SULRhejhoBWUmMnU53YHJrQZ3rxqsamdm',
        mapId: 12959,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
      },
      'PLENTY-kUSD-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1XTpd8JPexGxBL2dAmU9h2o9fcd9LEUG2t',
        mapId: 12963,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-XTZ-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1DMnJvNrFYc8N9Ptxhw3NtqKN7AWqxCpkS',
        mapId: 171168,
        READ_TYPE: 'FA1.2',
        CALL_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        DEX_PAIRS: {},
      },
      'Plenty-QUIPU-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1VDSyTqS95wkB4tRGy6saMa4izRKwrEg26',
        mapId: 12966,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'wWETH-ETHtz-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1GubVxQVJucUJfJvysvAJKWpLwj3LKuWHn',
        mapId: 12969,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
      },
      Plentywraplp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1AHndbp9xVpaJrfTHfYzSXKHDVHMdKxcW2',
        mapId: 14096,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 13,
        CALL_TYPE: 'FA1.2',
      },
      'Plenty-UNO-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1B6ALzWXQp5wUavuo2VTMNjRdTGm8wx37w',
        mapId: 14100,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 13,
        CALL_TYPE: 'FA1.2',
      },
      Plentykalamlp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1G3QTnrpWNhZr9x3Prprw3GH6gAMqV113D',
        mapId: 14104,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 14,
        CALL_TYPE: 'FA1.2',
      },
      'Plenty-SMAK-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1NLZah1MKeWuveQvdsCqAUCjksKw8J296z',
        mapId: 14107,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 10,
        CALL_TYPE: 'FA1.2',
      },
      PlentytzBTClp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1SqQimKz3RbQbckpSHhn4nanUmDuRqkFH3',
        mapId: 14093,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 13,
        CALL_TYPE: 'FA1.2',
      },
      'Plenty-uUSD-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1E8CrG6uznYAG9vZVGtApMJwwTScxPEUKq',
        mapId: 15796,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 14,
        CALL_TYPE: 'FA1.2',
      },
      PlentyGiflp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1MVLRQ7K7275oHDvbtKcUzNJsPBstZGKUp',
        mapId: 17061,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 13,
        CALL_TYPE: 'FA1.2',
      },
      'Plenty-YOU-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UaU5fbSYqYeFmhmsjLkqQXZ1ZG54Qs2vh',
        mapId: 20020,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 15,
        CALL_TYPE: 'FA1.2',
      },
      PlentywUSDTlp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1PcM1LUqgVdkXqKvZ4CeC9aiwLgYYCEHMH',
        mapId: 20024,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      PlentywDAIlp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT19vdNapeT6MALXvkvW745KiVKGXmD4AZq5',
        mapId: 20016,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        CALL_TYPE: 'FA1.2',
      },
      PlentyCtezlp: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1LdX5pUkZZGwYPePcAFSpETbqfbGCwJpfw',
        mapId: 21490,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'uusd-wusdc-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1A2W6mBjn49yqzjJbt9T7xNVD9gDeL45qD',
        mapId: 22767,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 9,
        CALL_TYPE: 'FA1.2',
      },
      'uusd-you-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1Tmncfgpp4ZSp6aEogL7uhBqHTiKsSPegK',
        mapId: 22770,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'uusd-udefi-LP': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1RQvdYD9yc763j8FiVLyXbKPVVbZqGRx5m',
        mapId: 22802,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-usdtz-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1DQfEUBsaZo43G3j1CbFF9BiWZXS72DuCh',
        mapId: 44781,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-wwbtc-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1XWRUcvtcgpsETcasdUnNkq9rJeWmz8ihD',
        mapId: 44790,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 7,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-wusdc-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1SXZTX9ZCW5atMnBng1y4pmdS2xi231oMt',
        mapId: 44803,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-wusdt-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1KgCx6CYVSyLxfiFdo5hVuMwZBPQy1XZaf',
        mapId: 44806,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-wbusd-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1K7GRKUWzfNJ9jzGprb13XDVqqp6GE67ZU',
        mapId: 44819,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-wdai-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1VLLdUaMfFbJw87b1PaVG1ac6UYM5xzqC5',
        mapId: 44829,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-kalam-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1N3mKQMnWEwt4FB3J4qP2X8LwYgndGDZrn',
        mapId: 44834,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 8,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-gif-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1KdPxrn7UTx6CUWxuUBaGx4bVv6ZJKWUWr',
        mapId: 44857,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 7,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-ethtz-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1GAvdLT9tkpKkRmkuChuL9T83esBtatgKm',
        mapId: 44870,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-quipu-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1C6Q4Mnnpns8vSQy7kJitZNMsED24SMw9m',
        mapId: 44884,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-hdao-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1DidqBuSaxGbVaDq2gLVkfh262dYyoGeSH',
        mapId: 44890,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-tzbtc-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1TMZjKBvSVKzETZTyRsTxYEu4uZLLs6VpJ',
        mapId: 44904,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 7,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-wweth-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1BAiXZkKG4R9W7LAKiAQahC8Wg7ZpJBaEs',
        mapId: 44916,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'ctez--lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1RQvdYD9yc763j8FiVLyXbKPVVbZqGRx5m',
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-uusd-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1BX8F7Xrtsy1tJ91iLovu4nJ8ZyVv4Dac2',
        mapId: 44924,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 9,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-smak-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1NeR3ExLddfdAbs5nwpQMm6DqBekyJTc4R',
        mapId: 44946,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 4,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-uno-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1WKWhTNMY4h4eHunbsnJ1oAtDWXCz4qNQm',
        mapId: 45316,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 7,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-kusd-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT19bFNh8pZCRtTy7Pi9kpEcb2Yd7KWArAik',
        mapId: 44750,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-wrap-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1MX73dim8HKqQLjTHvkJnpRUp37C1HXdkt',
        mapId: 44767,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 7,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-crunch-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1QSA2SMDEKzEnJhGrVGheWb94Ux8Wyfuy6',
        mapId: 44763,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 7,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-kdao-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1KmkH1T2CQV2Q5AcMeZy3GHhwNac48FBap',
        mapId: 44912,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 12,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-flame-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UfvQiYexnpag6rZ3LMGsn5YFiEHrXrtbq',
        mapId: 44943,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-crdao-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1MQcJCLZL8ASHYGmT5LVzeXV64ruy7RAuH',
        mapId: 44954,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 7,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-insta-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1GkTwzN2gR6UdBicDSu2JEaRtv5KAPunrj',
        mapId: 44957,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 7,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-pxl-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1GhzTxzgXgdv1rRCppAB5D4poXiUgp8yoU',
        mapId: 44994,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-paul-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1N93veCzepAPydFGGUhDFiA69PoawasxXi',
        mapId: 46392,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 7,
        CALL_TYPE: 'FA1.2',
      },
      'ctez-doga-lp': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1DZ41c1mV12oh8YNXm54JpwUNZ2C5R6VaG',
        mapId: 171789,
        READ_TYPE: 'FA1.2',
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 5,
        CALL_TYPE: 'FA1.2',
      },
    },
  },

  NETWORK: 'mainnet',
  WALLET_NETWORK: 'mainnet',
  ADMIN_ADDRESS: 'KT1GpTEq4p2XZ8w9p5xM7Wayyw5VR7tb3UaW',
  BURNER: 'tz1ZnK6zYJrC9PfKCPryg9tPW6LrERisTGtg',

  WRAPPED_ASSETS: {
    testnet: {
      wWBTC: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1VoHhkb6wXnoPDvcpbnPFYGTcpJaPfRoEh',
        mapId: 162869,
        TOKEN_ID: 19,
        TOKEN_DECIMAL: 8,
        REF_TOKEN: 'WBTC.e',
        READ_TYPE: 'FA2',
      },
      wWETH: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1VoHhkb6wXnoPDvcpbnPFYGTcpJaPfRoEh',
        mapId: 162869,
        TOKEN_ID: 20,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'WETH.e',
        READ_TYPE: 'FA2',
      },
      wBUSD: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1VoHhkb6wXnoPDvcpbnPFYGTcpJaPfRoEh',
        mapId: 162869,
        TOKEN_ID: 1,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'BUSD.e',
        READ_TYPE: 'FA2',
      },
      wUSDC: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1FcWdvGqggfaY4AuepEj2GjHBmk5jP33jE',
        mapId: 84170,
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 6,
        REF_TOKEN: 'USDC.e',
        READ_TYPE: 'FA2',
      },
      wUSDT: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1VoHhkb6wXnoPDvcpbnPFYGTcpJaPfRoEh',
        mapId: 162869,
        TOKEN_ID: 18,
        TOKEN_DECIMAL: 6,
        REF_TOKEN: 'USDT.e',
        READ_TYPE: 'FA2',
      },
      wMATIC: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1FcWdvGqggfaY4AuepEj2GjHBmk5jP33jE',
        mapId: 84170,
        TOKEN_ID: 2,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'MATIC.e',
        READ_TYPE: 'FA2',
      },
      wLINK: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1VoHhkb6wXnoPDvcpbnPFYGTcpJaPfRoEh',
        mapId: 162869,
        TOKEN_ID: 10,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'LINK.e',
        READ_TYPE: 'FA2',
      },
      wDAI: {
        ICON: '',
        TOKEN_CONTRACT: 'KT1VoHhkb6wXnoPDvcpbnPFYGTcpJaPfRoEh',
        mapId: 162869,
        TOKEN_ID: 5,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'DAI.e',
        READ_TYPE: 'FA2',
      },
      'WBTC.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1EZBn43coqL6xfT5xL6e49nhEPLp9B8m4n',
        mapId: 162915,
        TOKEN_ID: 4,
        TOKEN_DECIMAL: 8,
        REF_TOKEN: 'wWBTC',
        READ_TYPE: 'FA2',
      },
      'WETH.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1EZBn43coqL6xfT5xL6e49nhEPLp9B8m4n',
        mapId: 162915,
        TOKEN_ID: 5,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'wWETH',
        READ_TYPE: 'FA2',
      },
      'BUSD.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1EZBn43coqL6xfT5xL6e49nhEPLp9B8m4n',
        mapId: 162915,
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'wBUSD',
        READ_TYPE: 'FA2',
      },
      'USDC.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1AXQ7BgYgi8KBVhF3NmcdBNNTwyqXDC2vT',
        mapId: 84183,
        TOKEN_ID: 1,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'wUSDC',
        READ_TYPE: 'FA2',
      },
      'USDT.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1EZBn43coqL6xfT5xL6e49nhEPLp9B8m4n',
        mapId: 162915,
        TOKEN_ID: 3,
        TOKEN_DECIMAL: 6,
        REF_TOKEN: 'wUSDT',
        READ_TYPE: 'FA2',
      },
      'MATIC.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1AXQ7BgYgi8KBVhF3NmcdBNNTwyqXDC2vT',
        mapId: 84183,
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'wMATIC',
        READ_TYPE: 'FA2',
      },
      'LINK.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1EZBn43coqL6xfT5xL6e49nhEPLp9B8m4n',
        mapId: 162915,
        TOKEN_ID: 6,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'wLINK',
        READ_TYPE: 'FA2',
      },
      'DAI.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1EZBn43coqL6xfT5xL6e49nhEPLp9B8m4n',
        mapId: 162915,
        TOKEN_ID: 7,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'wDAI',
        READ_TYPE: 'FA2',
      },
    },
    mainnet: {
      wWBTC: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        TOKEN_ID: 19,
        TOKEN_DECIMAL: 8,
        REF_TOKEN: 'WBTC.e',
        READ_TYPE: 'FA2',
      },
      wWETH: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        TOKEN_ID: 20,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'WETH.e',
        READ_TYPE: 'FA2',
      },
      wBUSD: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        TOKEN_ID: 1,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'BUSD.e',
        READ_TYPE: 'FA2',
      },
      wUSDC: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        TOKEN_ID: 17,
        TOKEN_DECIMAL: 6,
        REF_TOKEN: 'USDC.e',
        READ_TYPE: 'FA2',
      },
      wUSDT: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        TOKEN_ID: 18,
        TOKEN_DECIMAL: 6,
        REF_TOKEN: 'USDT.e',
        READ_TYPE: 'FA2',
      },
      wMATIC: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        TOKEN_ID: 11,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'MATIC.e',
        READ_TYPE: 'FA2',
      },
      wLINK: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        TOKEN_ID: 10,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'LINK.e',
        READ_TYPE: 'FA2',
      },
      wDAI: {
        ICON: '',
        TOKEN_CONTRACT: 'KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ',
        mapId: 1772,
        TOKEN_ID: 5,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'DAI.e',
        READ_TYPE: 'FA2',
      },
      'WBTC.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        TOKEN_ID: 1,
        TOKEN_DECIMAL: 8,
        REF_TOKEN: 'wWBTC',
        READ_TYPE: 'FA2',
      },
      'WETH.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        TOKEN_ID: 0,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'wWETH',
        READ_TYPE: 'FA2',
      },
      'BUSD.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        TOKEN_ID: 7,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'wBUSD',
        READ_TYPE: 'FA2',
      },
      'USDC.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        TOKEN_ID: 2,
        TOKEN_DECIMAL: 6,
        REF_TOKEN: 'wUSDC',
        READ_TYPE: 'FA2',
      },
      'USDT.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        TOKEN_ID: 3,
        TOKEN_DECIMAL: 6,
        REF_TOKEN: 'wUSDT',
        READ_TYPE: 'FA2',
      },
      'MATIC.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        TOKEN_ID: 4,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'wMATIC',
        READ_TYPE: 'FA2',
      },
      'LINK.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        TOKEN_ID: 5,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'wLINK',
        READ_TYPE: 'FA2',
      },
      'DAI.e': {
        ICON: '',
        TOKEN_CONTRACT: 'KT1UsSfaXyqcjSVPeiD7U1bWgKy3taYN7NWY',
        mapId: 175082,
        TOKEN_ID: 6,
        TOKEN_DECIMAL: 18,
        REF_TOKEN: 'wDAI',
        READ_TYPE: 'FA2',
      },
    },
  },

  EXPLORER_LINKS: {
    RINKEBY: 'https://rinkeby.etherscan.io/tx/',
    ETHEREUM: 'https://etherscan.io/tx/',
    TEZOS: 'https://tzkt.io/',
  },
};

export default Config;
