import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Button from '../src/components/Button/Button';
import { SideBar } from '../src/components/Sidebar/sidebar';
import { SideBarHOC } from '../src/components/Sidebar/SideBarHOC';
import Tooltip from '../src/components/Tooltip/Tooltip';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
     <Head>
        <title className="font-medium1">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <SideBarHOC>
      
    </SideBarHOC>
    </div>
  );
};

export default Home;
