import type { NextPage } from 'next';
import Head from 'next/head';
import Button from '../src/components/Button/Button';
import { SideBarHOC } from '../src/components/Sidebar/SideBarHOC';
import Tooltip from '../src/components/Tooltip/Tooltip';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div>
     <Head>
        <title className="font-medium1">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <SideBarHOC>
       <div >
     
      <Button color="primary">CONNECT WALLET</Button>
      <main className={styles.main}>
        <Tooltip message="hi vgjhbkjnjkj">
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </Tooltip>
      </main>
    </div>
    </SideBarHOC>
    </div>
  );
};

export default Home;
