import type { NextPage } from 'next';
import PropTypes from 'prop-types';
import Head from 'next/head';
import Button from '../src/components/Button/Button';
import { PopUpModal } from '../src/components/Modal/popupModal';
import { SideBarHOC } from '../src/components/Sidebar/SideBarHOC';
import Swap from './Swap';
import { Provider } from 'react-redux';
import { store } from '../src/redux/index';
import {
  connectWallet,
  disconnectWallet,
} from '../src/redux/wallet/wallet.api';
import { useAppSelector } from '../src/redux/index';

const Home: NextPage = (props) => {
  const userAddress = useAppSelector((state) => state.wallet.address);

  const connectTempleWallet = async () => {
    if (userAddress === null) {
      return connectWallet();
    }
  };

  const disconnectUserWallet = async () => {
    if (userAddress) {
      return disconnectWallet();
    }
  };
  const otherPageProps = {
    connectWallet: connectTempleWallet,
    disconnectWallet: disconnectUserWallet,
    walletAddress: userAddress,
  };

  return (
<<<<<<< HEAD
    <Provider store={store}>
      <Head>
        <title className="font-medium1">Plent network</title>
        <meta name="description" content="plenty network" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBarHOC>
        <Swap otherProps={otherPageProps} />
      </SideBarHOC>
    </Provider>
=======
    <div>

     <Head>
        <title className="font-medium1">Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <SideBarHOC>
       <div >
     
      <Button color="primary">CONNECT WALLET</Button>
      <main className={styles.main}>
        <Tooltip message="hi vgjhbkjnjkj">
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </Tooltip>
      </main>
    </div>
    </SideBarHOC>
    </div>
>>>>>>> 14834d4613bfd8b43b65f1bc8e3c2de6b91d8cb5
  );
};
Home.propTypes = {
  connectWallet: PropTypes.any,
  disconnectWallet: PropTypes.any,
  fetchWalletAddress: PropTypes.any,
  userAddress: PropTypes.any,
};

export default Home;
